// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnlavmuowungqtteiecf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhubGF2bXVvd3VuZ3F0dGVpZWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDI2NDksImV4cCI6MjA3MjcxODY0OX0.oMQ8LxDBbF0VwzyreffgId-TMqu1GRBLFWNI_d-3eIo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});